
### OBTENER TODOS LOS USUARIOS

GET http://localhost:3000/api/usuarios


###OBTENER UN SOLO USUARIO
GET http://localhost:3000/api/usuarios/667cc6ea00b0edd7e5cc8988


###CREAR UN NUEVO USUARIO

POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "nombre": "Serena",
    "apellido": "Giacomelli",
    "dni": "4563806",
    "mail": "sere@gmail.com",
    "fechaNacimiento": "04/06/2004"
    
    
}

###MODIFICAR UN CHARACTER (PUT- modificar recurso completo e idempotente)
PUT http://localhost:3000/api/usuarios/667cc7a800b0edd7e5cc8989 
Content-Type: application/json

{
    "nombre": "Chiara",
    "apellido": "Leonardi",
    "dni": "45638062",
    "fechaNacimiento": "2000-05-25",
    "email": "seregiacomelli@gmail.com"
}

###MODIFICAR UN CHARACTER (PATCH- modificar recurso  de forma parcial)
PATCH http://localhost:3000/api/usuarios/667cc7a800b0edd7e5cc8989
Content-Type: application/json

{
    "nombre": "Maria Lucia",
    "apellido": "Munne",
    "dni": "45638062"
  
}

###ELIMINAR UN CHARACTER
DELETE http://localhost:3000/api/usuarios/667d6275eed7dfa923dedc38