### Obtener todos los usuarios

GET http://localhost:3000/api/usuarios

### Obtener un usuario por dni

GET http://localhost:3000/api/usuarios/2058365

### Crear un usuario

POST http://localhost:3000/api/usuarios/
Content-Type: application/json

{
    "dni": "4477799",
    "nombre": "Maria Lucia",
    "apellido": "Munne",
    "email": "marilu@gmail.com",
    "fechaNacimiento": "2001-02-14"
}

### modificar un usuario (PUT - recurso completo)

PUT http://localhost:3000/api/usuarios/2058365
Content-Type: application/json

{
    "dni": "14588605",
    "nombre": "Juan Jose",
    "apellido": "Giacomelli",
    "email": "juanjo@gmail.com",
    "fechaNacimiento": "1961-10-31"
}

### modificar un usuario (PATCH - recurso parcial)

PATCH http://localhost:3000/api/usuarios/12345678
Content-Type: application/json

{
    "email": "mailcambiado@gmail.com",
    "fechaNacimiento": "1995-05-10"
}

### Borrar un usuario

DELETE http://localhost:3000/api/usuarios/12345678